### ISSUE TITLE
can u give your opinion on this? spinlock. it's supposingly faster. can use on your lru?

### ISSUE THREAD

**Issue by ouvaa** [phuslu/lru#11]
https://github.com/daniel-hutao/spinlock

it seemed 5-10x faster so was wondering if it will faster

**Comment by phuslu** [comment]
I've tried spinlock/seqlock before, It decrease throughputs, let me give a try again...

**Comment by phuslu** [comment]
The spinlock integration is on `test-spinlock` branch and here is benchmark https://github.com/phuslu/lru/actions/runs/8409295475/job/23026467489

seems that there're no new findings/changes.

**Comment by phuslu** [comment]
xref https://github.com/daniel-hutao/spinlock/issues/1

**Comment by maypok86** [comment]
There are several things you need to understand here, because of which spinlocks are an unsuitable solution in most cases.

1. Spinlock is much superior to mutex in a single case. Namely, when the amount of work under lock is extremely small and the system creates a high contention for this lock. In this situation, the functionality of waiting for goroutines in the mutex becomes too expensive, and the spinlock feels pretty good. Unfortunately, this situation is extremely rare, but a situation in which an operation under lock takes more than 5-10ns is much more common and in it a spinlock can set your cpu on fire.
2. Most of the time in the cache benchmark is usually spent on cas operations and waiting for an exclusive lock. Even with such a small amount of work, a spinlock will not be better than a mutex. So it is better to use spinlocks only if you are absolutely sure that you understand what you are doing.

P.S. You can look at what I'm talking about in the benchmarks from this repository. There is only an incredibly cheap [operation](https://github.com/daniel-hutao/spinlock/blob/main/spinlock_test.go#L55) under lock.

**Comment by ouvaa** [comment]
@maypok86 thank you so much for the explanation. i couldnt really understand until you point out to the code section. thx!
